name: Release
on:
  push: { branches: [master] }
  workflow_dispatch:

permissions: write-all

jobs:
  build-everything:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  create-release:
    runs-on: ubuntu-latest
    needs: build-everything
    env: { GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Environment Variables
        run: |
          echo VERSION=`git describe --tags --abbrev=0 --match "v*" | tail -c +2` >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: ppm.*
          path: artifacts
          merge-multiple: true

      - name: Create Release(s)
        run: |
          perl -pe 'last if $_ =~ m/^\s*#/ && $_ !~ m/#\s*$ENV{VERSION}/' < CHANGELOG.md | tail -n +2 > NOTES.md
          gh release delete -y continuous || true;
          gh release create -t 'Continuous Release' -F NOTES.md continuous ./artifacts/*
          if [[ `git tag --points-at HEAD v* | head -c 1` == "v" ]]; then
            gh release delete -y v$VERSION || true;
            gh release create -t v$VERSION -F NOTES.md v$VERSION ./artifacts/*
            gh release delete -y latest || true;
            gh release create -t latest -F NOTES.md latest ./artifacts/*
            git branch -f latest HEAD
            git tag -f latest
            git push -f origin refs/heads/latest
            git push -f origin refs/tags/latest
          fi
          git tag -f continuous
          git push -f origin refs/tags/continuous
